"""empty message

Revision ID: 4eecb54b8aac
Revises: 36b93d81ad60
Create Date: 2015-03-04 12:04:51.449655

"""

# revision identifiers, used by Alembic.
revision = '4eecb54b8aac'
down_revision = '36b93d81ad60'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loguser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Dominik', sa.String(), nullable=False),
    sa.Column('Machura', sa.String(), nullable=False),
    sa.Column('pohlavi', sa.Boolean(name='zena'), nullable=True),
    sa.Column('datum_insertu', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_loguser'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_loguser_Machura', 'loguser', ['Machura'], unique=False)
    op.create_table('karty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('CISLO_KARTY', sa.String(), nullable=False),
    sa.Column('TIME', sa.DateTime(), nullable=False),
    sa.Column('WTIME', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_karty'),
    sqlite_autoincrement=True
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('karty')
    op.drop_index('ix_loguser_Machura', table_name='loguser')
    op.drop_table('loguser')
    ### end Alembic commands ###
